@startuml Warm house container
title Warm house Container Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "Client", "A user of the warm house service")
Person(OfficeManager, "Bank Manager", "The manager for iteracting with users")
Person(LoanManager, "Loan manager", "Loan manager")
Person(DepositManager, "Deposit manager", "Deposit manager")
System(BankSystem, "Bank System", "System of the bank.")
System_Ext(TelekomOperator, "Telekom operator", "Telekom for sending SMS")
System_Ext(ParnterCallCenter, "Partner call center", "Partner call center")
System_Ext(CreditHistory, "Bureau of credit history", "Users credit history")

Container_Boundary(BankSystem, "Warm House System") {
  Container(InternetBank, "Internet Bank", "ASP.NET", "Internet Banking")
  Container(InternetBankDb, "Database", "MS SQL", "Internet Banking Database")
  Container(WebSite, "Web site", "PHP & React.js", "Web site")
  Container(ABS, "ABS", "Delphi", "ABS")
  Container(ABSDb, "Database", "Oracle", "ABS database")
  Container(CallCenter, "Call Center", "Java Spring Boot", "Call center system")
  Container(CallCenterDb, "Database", "PostgreSQL", "Call center database")
  Container(SMSGateway, "SMS Gateway", "Gateway", "SMS Gateway system")
  Container(LoanOrigination, "Loan Origination", "Camunda", "Loan Origination")
  Container(LoanOriginationDb, "Database", "Oracle", "Loan Origination database")
  Container(LoanScoring, "Loan Scroing", "Python, Flaks", "Loang Scoring system")
  Container(LoanScoringDb, "Database", "PostgreSQL", "Loan Scoring database")
  Container(Kong, "Api Gateway", "Kong", "For balancing the traffic")
  Container(Kafka, "Kafka", "Kafka", "Kafka")
}


Rel(user, InternetBank, "Deposit/Loan info, Deposit/Loan requests")
Rel(user, WebSite, "Deposit/Loan info, Deposit/Loan requests")
Rel(user, OfficeManager, "Deposit/Loan info, Deposit/Loan requests")
Rel(user, ParnterCallCenter, "Making info calls")
Rel(user, CallCenter, "Gets info and set up pre requests")
Rel(TelekomOperator, user, "Deposit/Loand statuses and codes")
Rel(InternetBank, InternetBankDb, "Uses database")
Rel(CallCenter, CallCenterDb, "Uses database")
Rel(ABS, ABSDb, "Uses database")
Rel(SMSGateway, TelekomOperator, "Sends commands")
Rel(LoanOrigination, LoanOriginationDb, "Uses database")
Rel(LoanScoring, LoanScoringDb, "Uses database")
Rel(OfficeManager, ABS, "Deposit/Loan creation")
Rel(OfficeManager, WebSite, "Gets clients requests and sends to ABS")
Rel(OfficeManager, InternetBank, "Gets clients requests and sends to ABS")
Rel(LoanManager, CreditHistory, "Gets loan history")
Rel(LoanManager, ABS, "Set's the client status about credit")
Rel(LoanManager, LoanOrigination, "Gets new credit requests")
Rel(LoanManager, LoanScoring, "Sends data to get loan score")
Rel(ABS, SMSGateway, "Sends user request statuses")
Rel(DepositManager, ABS, "Gets deposits requests and sets stavkas")
Rel(DepositManager, LoanManager, "Sends request to get extra data")
Rel(DepositManager, InternetBank, "Gets deposti requests")
Rel(WebSite, CreditHistory, "Get users credit history")
Rel(WebSite, Kafka, "Send users notification about identification and loan")
Rel(OfficeManager, WebSite, "Continue working with users request")
Rel(InternetBank, Kafka, "Confirm Creidt getting")
Rel(InternetBank, LoanOrigination, "Gets full credit info")
Rel(WebSite, LoanOrigination, "Gets full creidt info")
Rel(SMSGateway, Kafka, "Gets sms events")
@enduml