@startuml

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(client, "client")
Person(internal_op, "Internal Call-Center Operator")
Person(partner_op,  "Partner Call-Center Operator")
System(bank, "Bank system")

Rel(client, internal_op, "Кносультация")
Rel(client, partner_op, "Консультация")
Rel(internal_op, bank, "Получение ставок")
Rel(bank, partner_op, "Отправляет по почте партнёру после обновления курсов")

@enduml
